---
# Create by Oshan Chamika 
# Mod Date:28/12/2024
- name: Java Installation and Configuration
  hosts: app_servers
  become: yes
  tasks:
    - name: Install Java
      package:
        name: java-11-openjdk
        state: present

    - name: Display Java Version
      command: java -version
      register: java_version_output
      ignore_errors: yes

    - name: Show Java Version Output
      debug:
        var: java_version_output.stdout

    - name: Configure JAVA_HOME in /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/jre-11-openjdk'
        state: present

    - name: Source /etc/environment to apply changes
      shell: source /etc/environment
      args:
        executable: /bin/bash
